server:
  port: 8080
  servlet:
    context-path: /ws-sesp-anoreg
spring:
  application:
    name: anoreg-service
management:
  endpoints:
    web:
      exposure:
        include:
        - '*'
openapi:
  service:
    title: Anoreg service API #title that you will want to display in the swagger ui
    version: 1.0.0 
    description: Documentacao da API de integração com Anoreg (importe link acima via Postman para teste)
    url: http://localhost:8080 #api gateway url