server:
  port: 8080
spring:
  application:
    name: ws-sesp-anoreg
  config:
    import: 
      - optional:http://localhost:8888/
management:
  endpoints:
    web:
      exposure:
        include:
          - '*'
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
config:
  key: ANGB63EBB61DBCFE7
  secret: f30828c97a23c6d422cb7325079f2d57aca6235c
openapi:
  service:
    url: http://localhost:8080 #api gateway local