keycloack-config:
  url-server: https://dev2.sesp.mt.gov.br
  realm: SESP
  client-id: anoreg-api
  client-secret: 4Mh6ENzuWV90cRLctgJGDZeCHzqMDF4n
  redirect-uri: /login/oauth2/code/keycloak

service-discovery-config:
  url-server: https://dev2.sesp.mt.gov.br/ws-sesp-service-discovery

gateway-config:
  url-server: http://localhost:8765

spring:
  security:
    oauth2:
      client:
        provider:
          my-keycloak-provider:
            issuer-uri: ${keycloack-config.url-server}/auth/realms/${keycloack-config.realm}
        registration:
          keycloak-spring-gateway-client:
            provider: my-keycloak-provider
            scope: openid
            client-id: ${keycloack-config.client-id}
            client-secret: ${keycloack-config.client-secret}
            authorization-grant-type: authorization_code
            redirect-uri:  ${gateway-config.url-server}${keycloack-config.redirect-uri}

management:
  endpoints:
    web:
      exposure:
        include:
          - actuator
          - info
          - refresh

eureka:
  client:
    service-url:
      defaultZone: ${service-discovery-config.url-server}/eureka

config:
  key: ANGB63EBB61DBCFE7
  secret: f30828c97a23c6d422cb7325079f2d57aca6235c
openapi:
  service:
    url: http://localhost:8080 #api gateway local
